-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 10:39:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accountingapp_jc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accountingapp_jc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accountingapp_jc` DEFAULT CHARACTER SET utf8 ;
USE `accountingapp_jc` ;

-- -----------------------------------------------------
-- Table `accountingapp_jc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `role` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `address` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`productcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`productcategory` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(500) NULL,
  `status` INT(2) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productcategory_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_productcategory_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`productbrand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`productbrand` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(500) NULL,
  `status` VARCHAR(2) NULL,
  `productbrandcol` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productbrand_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_productbrand_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`taxes` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `value` DOUBLE NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_taxes_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_taxes_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`productunit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`productunit` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productunit_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_productunit_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(500) NULL,
  `status` INT(2) NULL,
  `minstock` DOUBLE NULL,
  `size` VARCHAR(256) NULL,
  `barcode` VARCHAR(1500) NULL,
  `company_id` INT NOT NULL,
  `productunit_id` INT NOT NULL,
  `productbrand_id` INT NOT NULL,
  `productcategory_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_product_productunit1_idx` (`productunit_id` ASC) VISIBLE,
  INDEX `fk_product_productbrand1_idx` (`productbrand_id` ASC) VISIBLE,
  INDEX `fk_product_productcategory1_idx` (`productcategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_productunit1`
    FOREIGN KEY (`productunit_id`)
    REFERENCES `accountingapp_jc`.`productunit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_productbrand1`
    FOREIGN KEY (`productbrand_id`)
    REFERENCES `accountingapp_jc`.`productbrand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_productcategory1`
    FOREIGN KEY (`productcategory_id`)
    REFERENCES `accountingapp_jc`.`productcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`productpricing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`productpricing` (
  `id` INT NOT NULL,
  `purchaserate` DOUBLE NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `salerate` DOUBLE NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productpricing_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_productpricing_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `accountingapp_jc`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`suppliers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `phone` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`company_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`company_has_user` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`currency` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_currency_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_currency_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`accountgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`accountgroups` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `nature` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accountgroups_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_accountgroups_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`accountledger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`accountledger` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `accountgroups_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accountledger_accountgroups1_idx` (`accountgroups_id` ASC) VISIBLE,
  CONSTRAINT `fk_accountledger_accountgroups1`
    FOREIGN KEY (`accountgroups_id`)
    REFERENCES `accountingapp_jc`.`accountgroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`vouchertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`vouchertype` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchasequotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchasequotation` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchasequotation_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchasequotation_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `accountingapp_jc`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchasequotationlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchasequotationlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `purchasequotation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchasequotationlist_purchasequotation1_idx` (`purchasequotation_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchasequotationlist_purchasequotation1`
    FOREIGN KEY (`purchasequotation_id`)
    REFERENCES `accountingapp_jc`.`purchasequotation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`salequotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`salequotation` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salequotation_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_salequotation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `accountingapp_jc`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`salequotationlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`salequotationlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `salequotation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salequotationlist_salequotation1_idx` (`salequotation_id` ASC) VISIBLE,
  CONSTRAINT `fk_salequotationlist_salequotation1`
    FOREIGN KEY (`salequotation_id`)
    REFERENCES `accountingapp_jc`.`salequotation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purcahseorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purcahseorder` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purcahseorder_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_purcahseorder_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `accountingapp_jc`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchaseorderlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchaseorderlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `purcahseorder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchaseorderlist_purcahseorder1_idx` (`purcahseorder_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchaseorderlist_purcahseorder1`
    FOREIGN KEY (`purcahseorder_id`)
    REFERENCES `accountingapp_jc`.`purcahseorder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`saleorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`saleorder` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_saleorder_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_saleorder_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `accountingapp_jc`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`saleorderlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`saleorderlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `saleorder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_saleorderlist_saleorder1_idx` (`saleorder_id` ASC) VISIBLE,
  CONSTRAINT `fk_saleorderlist_saleorder1`
    FOREIGN KEY (`saleorder_id`)
    REFERENCES `accountingapp_jc`.`saleorder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`saleinvoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`saleinvoice` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_saleinvoice_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_saleinvoice_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `accountingapp_jc`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`salereturn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`salereturn` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salereturn_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_salereturn_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `accountingapp_jc`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`saleinvoicelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`saleinvoicelist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `saleinvoice_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_saleinvoicelist_saleinvoice1_idx` (`saleinvoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_saleinvoicelist_saleinvoice1`
    FOREIGN KEY (`saleinvoice_id`)
    REFERENCES `accountingapp_jc`.`saleinvoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`salereturnlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`salereturnlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `salereturn_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salereturnlist_salereturn1_idx` (`salereturn_id` ASC) VISIBLE,
  CONSTRAINT `fk_salereturnlist_salereturn1`
    FOREIGN KEY (`salereturn_id`)
    REFERENCES `accountingapp_jc`.`salereturn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchaseinvoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchaseinvoice` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchaseinvoice_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchaseinvoice_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `accountingapp_jc`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchasereturn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchasereturn` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `remark` VARCHAR(500) NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchasereturn_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchasereturn_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `accountingapp_jc`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchaseinvoicelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchaseinvoicelist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `purchaseinvoice_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchaseinvoicelist_purchaseinvoice1_idx` (`purchaseinvoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchaseinvoicelist_purchaseinvoice1`
    FOREIGN KEY (`purchaseinvoice_id`)
    REFERENCES `accountingapp_jc`.`purchaseinvoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`purchasereturnlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`purchasereturnlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qty` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `purchasereturn_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchasereturnlist_purchasereturn1_idx` (`purchasereturn_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchasereturnlist_purchasereturn1`
    FOREIGN KEY (`purchasereturn_id`)
    REFERENCES `accountingapp_jc`.`purchasereturn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`user_has_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`user_has_company` (
  `user_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `company_id`),
  INDEX `fk_user_has_company_company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_user_has_company_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_company_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `accountingapp_jc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_company_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `accountingapp_jc`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountingapp_jc`.`product_has_taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingapp_jc`.`product_has_taxes` (
  `product_id` INT NOT NULL,
  `taxes_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `taxes_id`),
  INDEX `fk_product_has_taxes_taxes1_idx` (`taxes_id` ASC) VISIBLE,
  INDEX `fk_product_has_taxes_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_taxes_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `accountingapp_jc`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_taxes_taxes1`
    FOREIGN KEY (`taxes_id`)
    REFERENCES `accountingapp_jc`.`taxes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
